name: 'Continuous Delivery'

on:
  push:
    branches:
      - main
      - feature_deployment_gcp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: latam-mle-app
      AR_REPO_NAME: latam-mle-app-repo
      REGION: us-central1
      IMAGE_TAG: ${{ github.run_id }}-${{ github.sha }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up gcloud CLI
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO_NAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO_NAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy ${{ env.APP_NAME }} \
          --image ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.AR_REPO_NAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8000

    - name: Verify Service URL
      run: |
        gcloud run services describe ${{ env.APP_NAME }} \
        --platform managed \
        --region ${{ env.REGION }} \
        --format="value(status.url)"
