name: 'Continuous Delivery'

on:
  push:
    branches:
      - main
      - feature_deployment_gcp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: latam-mle-app
      REGION: us-central1
      IMAGE_TAG: ${{ github.run_id }}-${{ github.sha }}
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/latam-mle-app:${{ github.run_id }}-${{ github.sha }}

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set up gcloud CLI
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.run_id }}-${{ github.sha }} .

    - name: Push Docker image to Google Container Registry (GCR)
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.run_id }}-${{ github.sha }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy ${{ env.APP_NAME }} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APP_NAME }}:${{ github.run_id }}-${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8000

    - name: Verify Service URL
      run: |
        gcloud run services describe ${{ env.APP_NAME }} \
        --platform managed \
        --region ${{ env.REGION }} \
        --format="value(status.url)"
